version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=Akila the prod
    ports:
      - "8080:80"
    env_file:
      - ./.env
    environment:
      - REACT_APP_NAME=akila-prod
